apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jwpb8cjxd-nodejs
  janus-idp.io/tekton: jwpb8cjxd-nodejs
  backstage.io/kubernetes-id: jwpb8cjxd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jwpb8cjxd-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
